### ISSUE TITLE
Remove references to other IRC networks + mailing lists

### ISSUE THREAD

**Issue by staticfox** [kvirc/kvirc-www#22]
Basically treat the two means of communications for KVIrc to #KVIrc on freenode and @pragmaware's email (That's how I recall initially contacting him, personally). I sort of doubt anyone checks the mailing list (if you do. please speak up!), I've already verified the other IRC channels are effectively dead, and I think we've come to a consensus that most, if not all support will be spoken only in English. So rather then listing the many ways to communicate with us on the site, centralize it all.

**Comment by un1versal** [comment]
+1 for simple, central and effective way to do this.

We have one IRC channel the GitHub issues and that should be enough.

The rest never had a single reply from or anything ever come of it in the last 5 years.

**Comment by un1versal** [comment]
KVIrc still has mailing list on menu but imo that ancient crap noone check and very very few people use should die in a fire and upgrade to 2016 methods

problem is who check ANYTHING these days? I send emails out to some team members and they including pragma dont check them, so email imo is useless.

**Comment by ctrlaltca** [comment]
Removed references to the mailing list from the website, pointed to the github issues instead.
