### ISSUE TITLE
svn.kvirc.de going out of service

### ISSUE THREAD

**Issue by waja** [kvirc/kvirc-www#27]
Hi there,

svn.kvirc.de is going out of service (as announced many times). Anyway, it is still part of the infrastructure, at least for mirroring FTP. https://github.com/kvirc/kvirc-www/blob/master/content/mirroring.php#L29 and https://github.com/kvirc/kvirc-www/blob/master/content/mirroring.php#L43 references it.

It would be very good to move this dependency away to another resource (or create another mechanism) as I can't promise how long this service will be alive, the hardware is more then 10 years old.

**Comment by waja** [comment]
Nobody is caring? So why should I still do ... *sigh*

**Comment by wodim** [comment]
Many of us care, we just don't have any ideas or the time/resources to step forward.

I personally am not sure we need an ftp server anymore, since we simply can upload our releases to github. But I'm sure somebody else has something else to say, etc.

**Comment by waja** [comment]
> Many of us care, we just don't have any ideas or the time/resources to step forward.

But also this is an information.

Please discuss your needs and come up with an proposal how to proceed. Keeping the burden on other people just because nobody is willing to step forward isn't very smart.

**Comment by wodim** [comment]
If I understood your message correctly, you told us the master ftp might go out of service at any moment because the hardware is old. We received the message, and if that happens, we will only have ourselves to blame.

Or do you mean to say you want to shut down the server now, but you're still waiting on us?

**Comment by ctrlaltca** [comment]
If nobody wants to pick up and manage the ftp, i'd suggest dropping ftp at all.
Before we do that, we need to ensure that all the content is currently available somewhere else:

- [ ] source releases: from 3.4.0 on they are already tagged on github, previous are missing
- [ ] binary releases: not available anywhere
- [x] addons: already hosted at https://github.com/kvirc/kvirc-scripts
- [ ] scripts: not available anywhere, probably useless if not from an historical POV
- [ ] snapshots: contains outdated unofficial binary releases, i'd drop them for good
- [x] themes: they should be merged at https://github.com/kvirc/kvirc-themes
- [ ] tools: check if they are still useful, then create another repo?
- [ ] tutorials: they should be probably moved into their own repo and converted to something user-editable (es. github pages, wiki, markdown, ...)

Once everything has been moved in place, we'll need to update all the links in the website.

Your opinions good sirs?

**Comment by wodim** [comment]
What if we upload the stuff that has historical but no practical value (such as old source tarballs and binaries) to archive.org ?

**Comment by waja** [comment]
> Or do you mean to say you want to shut down the server now, but you're still waiting on us?

Actually the system is running (and I take care for system maintenance), but it can stop working at any time. And I would also prefer to be able to stop to maintain the whole stack for various reasons.

**Comment by waja** [comment]
> > Or do you mean to say you want to shut down the server now, but you're still waiting on us?
>
> Actually the system is running (and I take care for system maintenance), but it can stop working at any
> time. And I would also prefer to be able to stop to maintain the whole stack for various reasons.

As I again had to invest resources to keep this system alive. Is there any chance to move the FTP (distribution mechanism) away (soon)?
I would hate myself to keep you out there in the rain if the system is not recoverable anymore sometime.

**Comment by waja** [comment]
```
svn.kvirc.de:~# /etc/init.d/apache2 stop
[ ok ] Stopping web server: apache2 ... waiting .
svn.kvirc.de:~# /etc/init.d/bind9 stop
[....] Stopping domain name service...: bind9waiting for pid 1658 to die
. ok
svn.kvirc.de:~# /etc/init.d/xinetd stop
[ ok ] Stopping internet superserver: xinetd.
svn.kvirc.de:~# cat /etc/debian_version
7.11
```

Thank you for your attention to this matter and your understanding.

**Comment by waja** [comment]
System is done away.
