### ISSUE TITLE
Unmaintained kvirc dot net website

### ISSUE THREAD

**Issue by abazaba855** [kvirc/kvirc-www#29]
The entire www.kvirc.net website seems to be completely abandoned for a long time now, I wonder if the current maintainers even have control over the website anymore. A lot of the links to downloads (themes, 'official downloads') are through ftp even though browsers stopped supporting that protocol a long time ago, the 'www mirror' of www.kvirc.de isnt even registered in DNS anymore, the mailing list related links point to lists.omnikron.net that isnt registered in DNS anymore either, when going to "KVIrc related" on the top right bar the 'Official forum' and 'Russian site' links arent registered in DNS anymore, the screenshots under 'the project -> screenshots' are from kvirc 3.2.6, etc.

(reporting the same issue over here, as "Broken links on website kvirc dot net [#2524](https://github.com/kvirc/KVIrc/issues/2524#issue)" in the kvirc repo, as informed by @ctrlaltca over here : https://github.com/kvirc/KVIrc/issues/2524#issuecomment-1869117807 )

**Comment by knakamura8** [comment]
Replicating here for ease:

Bugs:

- [x] http://www.kvirc.net/?id=status&lang=en references 4.2.0 Equilibrium, rather than 5.0.0 Aria
- [x]  http://www.kvirc.net/?id=download&lang=en references 4.2.0 Equilibrium, rather than 5.0.0 Aria
- [x]  http://www.kvirc.net/ Top right links to Official forum and Russian site are both dead

Suggests:

- [ ] Replace Official forum and Russian site links with archive links

**Comment by pragmaware** [comment]
www.kvirc.net has been resurrected. See [here](https://github.com/kvirc/KVIrc/issues/2524#issuecomment-1891022170)

**Comment by abazaba855** [comment]
Thanks ! I indeed no longer get that strange request to authenticate with a cert when I connect. Of course, this specific issue is about the actual contents of the site, which needs some serious updates (for example as posted above, but there are more examples).

**Comment by ctrlaltca** [comment]
Fixed the issues reported on this ticket.

**Comment by abazaba855** [comment]
Thanks. I looked at the updated website, and a quick glance only seemed to turn up this : 
The web site still points to FTP links (for example mirrors: ftp.kvirc.net, and the 'themes' downloads) which is a protocol that has been removed from all major browsers ages ago. In my opinion these should really be updated to HTTPS.
