### ISSUE TITLE
export from kvirc/kvirc

### ISSUE THREAD

**Issue by SolarAquarion** [kvirc/kvirc-www#6]
http://www.kvirc.net/doc/doc_python_and_kvs.html

Passing parameters to the python script

```
python.begin("","Hello world!","Now I CAN",1,2,3)
for(i=0;i<5;i++)
    kvirc.echo(aArgs,40)
python.end
```

that is not python code, the ++ and -- operators don't exist in Python, the python way to do it is like this
(a direct version of the example above):

```
python.begin("","Hello world!","Now I CAN",1,2,3)
i = 0
while i<5:
    kvirc.echo(aArgs[1])
    i+=1
python.end
```

but using range is more efficient:

```
python.begin("","Hello world!","Now I CAN",1,2,3)
for l in range(0,5):
    kvirc.echo(aArgs[l])
python.end
```

and maybe someone could put a note somewhere where it say that aArgs is a list

and one more question:

```
%pippo = test
%Pluto = 12345
python.begin
mypippo = kvirc.getLocal("pippo")
mypippo += " rox"
mypluto = kvirc.getGlobal("Pluto")
mypluto += " rox"
kvirc.setLocal("pippo",mypluto) # here
kvirc.setGlobal("Pluto",mypippo) # and here
python.end
echo "\%pippo is" %pippo
echo "\%Pluto is" %Pluto
```

why did someone swap the variable?
not only will it confusing when someone miss read it, there also no need to swap them, it should just be:

```
kvirc.setLocal("pippo",mypippo)
kvirc.setGlobal("Pluto",mypluto)
```

**Comment by pragmaware** [comment]
I have fixed the documentation in the KVIrc source code.
